---
name: Joakim
surname: Frögren
address: |
    | Edward Lindahlsgatan 9 \newline 217 42 Malmö
phone: +46 73 516 12 12
profilepic: joakim.png
email: "joakim@frogren.se"
date: "Födelsedatum: 31 oktober 1979"
aboutme: "Mitt intresse för människor, kommunikation och hälsa löper som en röd tråd genom mitt liv, och har gett mig en bred palett av kunskap av såväl teoretisk som praktisk natur. \\newline \\newline Efter erhållen doktorsexamen och en periods arbete ute på fältet, ser jag det nu som en naturlig fortsättning att åter söka mig till akademin. \\newline \\newline Tjänsten som lektor hos er lockar mig därför att jag vet att ni är en högskola i framkant när det gäller hälsoinriktad utbildning och forskning, och jag vill gärna var med och bidra och därigenom utvecklas. \\newline \\newline Jag får ofta höra att jag är en god pedagog med stort tålamod för människors varierande förutsättningar, inte minst framkom det under min tid som lärare i svenska som andraspråk. \\newline \\newline  Med min gedigna utbildning, omfångsrika kompetens och nyfikna inställning är jag övertygad om att jag blir en tillgång hos er."
output: vitae::twentyseconds
linkcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Akademiska examina

```{r}
library(tibble)
tribble(
  ~ What, ~ Year, ~ Institution, ~ Where,
  "Doktorsexamen i medicinsk vetenskap", "2023", "\\href{https://portal.research.lu.se/en/publications/on-user-involvement-in-research-on-ageing-and-health}{Länk till avhandlingen}", "Lunds universitet",
  "Magisterexamen i kognitionsvetenskap", "2013", "", "Linköpings universitet"
) %>% 
  detailed_entries(What, Year, Institution, Where,
                   .protect = FALSE)
```
<!--
# Vetenskapliga arbeten

```{r}
library(tibble)
tribble(
  ~what, ~year,
  "\\href{https://portal.research.lu.se/en/publications/on-user-involvement-in-research-on-ageing-and-health}{Frögren, J. (2023). On User Involvement in Research on Ageing and Health. [Doctoral Thesis, Department of Health Sciences]. Lund University, Faculty of Medicine.}", "Avhandling",
) %>% 
  brief_entries(
    what, year,
    .protect = FALSE
  )
```
-->
# Presentationer av min forskning
<!--
- 20 april 2023 - Avslutningskonferens för forskningsprogrammet UserAge, Lund (https://www.medicin.lu.se/evenemang/avslutningskonferens-userage)
- 18 oktober 2022 Webbinarie om fysiska hinder i svenska hem, Stockholm (https://www.youtube.com/watch?v=z5JId15gq9w&t=25m21s) 
- 7 november 2019 CASE-dagen (Centre for Ageing & Supportive Environments),Lund  (https://www.youtube.com/watch?v=S2LeICgasAo)
- 7-11 maj 2018 11th World Conference of Gerontechnology i St. Petersburg, Florida (https://journal.gerontechnology.org/pastIssuesList.aspx?iid=112)

-->
```{r}
library(tibble)
tribble(
  ~ What, ~ Year, ~ Institution, ~ Where,
  "Avslutningskonferens för forskningsprogrammet UserAge, Lund", "2023", "", "Presentation av de fyra studierna i avhandlingen",
  "Webbinarie om Bostadsförsöket, Stockholm", "2022", "\\href{https://www.youtube.com/watch?v=z5JId15gq9w&t=25m21s}{Länk till min redogörelse}", "Redogörelse för resultatet i fjärde delstudien i avhandlingen",
  "CASE-dagen, Lund", "2019", "\\href{https://www.youtube.com/watch?v=S2LeICgasAo}{Länk till min presentation}", "Presentation av andra delstudien i avhandlingen",
  "11th World Conference of Gerontechnology, St. Pete., Florida", "2018", "", "Presentation av abstract från första delstudien i avhandlingen"
) %>% 
  detailed_entries(What, Year, Institution, Where,
                   .protect = FALSE)
```

# Övrig utbildning utöver den examensgrundande
```{r}
library(tibble)
tribble(
  ~ What, ~ Year, ~ Institution, ~ Where,
  "Litterära perspektiv på sjukdom och död (7,5 hp)", "2024-", "", "Lunds universitet",
  "Doktorandstudier i tillämpad hälsovetenskap", "2016-2018", "", "Blekinge tekniska högskola",
  "Svenska som andraspråk 1 (30 hp)", "2014-2015", "", "Linköpings universitet",
  "Engelska A (30 hp)", "2005-2006", "", "Linköpings universitet"
) %>% 
  detailed_entries(What, Year, Institution, Where,
                   .protect = FALSE)
```

# Arbetslivserfarenhet
```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Handledare inom socialpsykiatrin, Lunds kommun", "2023-", "", "Ge stöd och vård till personer med psykisk funktionsnedsättning",
  "Kundhjälpmedelsansvarig, Ikea, Stockholm", "2015-2016", "", "Ansvara för logistik av kundhjälpmedel och arbetsleda kollegor",
  "Lärare i svenska som andraspråk, Folkuniversitetet, Linköping", "2015", "", "Organisera och leda utbildning i yrkessvenska (halvårsvikariat)",
  "Taltjänsttolk vid Tolkcentralen, Region Östergötland, Linköping", "2004-2015", "", "Genom alternativ- och kompletterande kommunikation (AKK) stötta personer med tal- och språksvårigheter i att kommunicera självständigt"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```
<!--
"EU:s ungdomsprogram, del 3: Framtidssatsning, Vilnius, Litauen", "2004-2005", "", "I samarbete med Film i Sörmland och Kriminellas Revansch i Samhället (KRIS) producera och regissera en kortfilm och turnera med filmen i svenska gymnasieskolor",
  "EU:s ungdomsprogram, del 2: Volontärtjänst, Lyon, Frankrike", "2001-2002", "", "Tillsammans med franska ungdomar planera och bedriva sociala projekt i samarbete med olika organisationer och företag",
  "Personlig assistent, Umeå kommun", "2000-2001", "", "Stötta en person med muskelsjukdom med de dagliga aktiviteterna"
-->

# Språkkunskaper
```{r}
tribble(
  ~a, ~b,
  "Modersmål", "Svenska",
  "Flytande","Engelska",
  "Mycket goda kunskaper","Franska",
  "Grundläggande kunskaper", "Italienska"
) %>% 
  brief_entries(
    a, 
    b
  )
```


# IT-kunskaper
```{r}
tribble(
  ~a, ~b,
  "Mac OS X", "Mycket goda kunskaper",
  "Windows 11", "Mycket goda kunskaper",
  "Office 2021", "Mycket goda kunskaper",
  "SPSS 29", "Goda kunskaper", 
  "REDCap", "Goda kunskaper",  
  "R (RStudio)", "Grundläggande kunskaper",
) %>% 
  brief_entries(
    b, 
    a
  )
```

<!--
# Publikationer

```{r publications} 
bibliography_entries("library.bib", "Publications") 


``` 
-->
